name: Deploy frontend

on:
  push:
    branches:
      - vps-static
      # - master
  workflow_dispatch:

jobs:
  clone-build-send-front:
    name: Clone front, build in docker, send to vps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.PAT }}
      - name: Build
        run: >
          chmod +x ./deploy-entrypoint-build.sh &&
          
          REACT_APP_API_URL=${{ secrets.CORS_URL }}
          /bin/bash ./deploy-entrypoint-build.sh

      - name: Scp send
        uses: appleboy/scp-action@v0.1.4
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          rm: true
          overwrite: true
          strip_components: 0
          source: './*'
          target: '/root/code/wa-static'

  run-host:
    name: Launch front static hosting
    needs: [clone-build-send-front]
    runs-on: ubuntu-latest

    steps:
      - name: Build & Run host
        uses: appleboy/ssh-action@v0.1.4
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: >
            cd /root/code/wa-static &&
            chmod +x ./deploy-entrypoint-build.sh &&

            VIRTUAL_HOST=${{ secrets.VIRTUAL_HOST }}
            LETSENCRYPT_HOST=${{ secrets.LETSENCRYPT_HOST }}
            /bin/bash ./deploy-entrypoint-host.sh
