name: Deploy frontend

on:
  push:
    branches:
      - vps-static
      # - master
  workflow_dispatch:

jobs:
  clone-build-send-front:
    name: Clone frontend from monorepo, build in docker, send to vps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: checkout + build
        run: >
          chmod +x ./deploy-entrypoint-build.sh &&
          
          REACT_APP_API_URL=${{ secrets.CORS_URL }} ./deploy-entrypoint-build.sh

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@v0.1.4
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          rm: true
          overwrite: true
          strip_components: 0
          source: './*'
          target: '/root/code/wa-static'

  run-host:
    name: Launch frontend static hosting
    needs: [clone-build-send-front]
    runs-on: ubuntu-latest

    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@v0.1.4
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: >
            cd /root/code/wa-static &&
            chmod +x ./deploy-entrypoint-build.sh &&

            VIRTUAL_HOST=${{ secrets.VIRTUAL_HOST }}
            LETSENCRYPT_HOST=${{ secrets.LETSENCRYPT_HOST }}
            ./deploy-entrypoint-run.sh
